# Generated by Django 3.0 on 2022-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220710_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
